# Generated by Django 6.0.5 on 2026-05-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbiesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbies',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='specie',
        ),
    ]
