# Generated by Django 6.0.5 on 2026-05-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbiesApp', '0002_remove_hobbies_bio_remove_hobbies_specie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
